// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNREkUb4yy5NYYMCbc163xFuugHDwj4iA',
    appId: '1:490492139041:web:d2a20926304d0f0ce53560',
    messagingSenderId: '490492139041',
    projectId: 'lullacare',
    authDomain: 'lullacare.firebaseapp.com',
    storageBucket: 'lullacare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycOufH_YfL00zLwV_simH8hzuKc2Ks3M',
    appId: '1:490492139041:android:35f01f8995dc216fe53560',
    messagingSenderId: '490492139041',
    projectId: 'lullacare',
    storageBucket: 'lullacare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2qNpy-13Go7TXFUwmr3KQE5ccF5BtJM',
    appId: '1:490492139041:ios:b6e04ecaafdc1b94e53560',
    messagingSenderId: '490492139041',
    projectId: 'lullacare',
    storageBucket: 'lullacare.firebasestorage.app',
    iosBundleId: 'fyp.julina.fypInfantMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2qNpy-13Go7TXFUwmr3KQE5ccF5BtJM',
    appId: '1:490492139041:ios:b6e04ecaafdc1b94e53560',
    messagingSenderId: '490492139041',
    projectId: 'lullacare',
    storageBucket: 'lullacare.firebasestorage.app',
    iosBundleId: 'fyp.julina.fypInfantMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNREkUb4yy5NYYMCbc163xFuugHDwj4iA',
    appId: '1:490492139041:web:663b21ace2e76d73e53560',
    messagingSenderId: '490492139041',
    projectId: 'lullacare',
    authDomain: 'lullacare.firebaseapp.com',
    storageBucket: 'lullacare.firebasestorage.app',
  );

}